[package]
name = "otap-df-validation"
description = "Performs validation for encoding/decoding and pipelines with OTLP/OTAP requests"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
linkme = "0.3"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_yaml = "0.9.34-deprecated" 
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
minijinja = "1"
tokio-util = { workspace = true }
tokio = { workspace = true }

weaver_common = { git = "https://github.com/open-telemetry/weaver.git", tag = "v0.17.0"}
weaver_forge = { git = "https://github.com/open-telemetry/weaver.git", tag = "v0.17.0" }
weaver_resolved_schema = { git = "https://github.com/open-telemetry/weaver.git", tag = "v0.17.0"}
weaver_resolver = { git = "https://github.com/open-telemetry/weaver.git", tag = "v0.17.0"}
weaver_semconv = { git = "https://github.com/open-telemetry/weaver.git", tag = "v0.17.0"}

otap-df-engine = { path = "../engine" }
otap-df-channel = { path = "../channel" }
otap-df-config = { path = "../config" }
otap-df-pdata = { path = "../pdata" }
otap-df-telemetry = { path = "../telemetry" }
otap-df-telemetry-macros = { path = "../telemetry-macros" }
otap-df-otap = { path = "../otap" }
otap-df-controller = { path = "../controller" }
