settings:
  default_pipeline_ctrl_msg_channel_size: 100
  default_node_ctrl_msg_channel_size: 100
  default_pdata_channel_size: 100

nodes:
  receiver:
    type: traffic_generator:receiver
    config:
      traffic_config:
        max_batch_size: 1000
        signals_per_second: 1000
        log_weight: 100
      registry_path: https://github.com/open-telemetry/semantic-conventions.git[model]
  debug:
    type: debug:processor
    outputs: ["passthrough_port", "logging_port"]
    config:
      verbosity: basic
      output:
        - logging_port
  debug2:
    type: debug:processor
    config:
      verbosity: normal
  noop:
    type: noop:exporter
    config:
  noop2:
    type: noop:exporter
    config:

connections:
  - from: receiver
    to: debug
  - from: debug["passthrough_port"]
    to: noop
  - from: debug["logging_port"]
    to: debug2
  - from: debug2
    to: noop2
