settings:
  default_pipeline_ctrl_msg_channel_size: 100
  default_node_ctrl_msg_channel_size: 100
  default_pdata_channel_size: 100

nodes:
  receiver:
    kind: receiver
    plugin_urn: "urn:otel:otel:receiver"
    out_ports:
      out_port:
        destinations:
          - perf
        dispatch_strategy: round_robin
    config:
      listening_addr: "127.0.0.1:4328"
      request_compression: none
      timeout: "10s"
  perf:
    kind: exporter
    plugin_urn: "urn:otel:otap:perf:exporter"
    config:
      frequency: 1000
      display_throughput: true
      cpu_usage: true
      mem_usage: true
      disk_usage: false
      io_usage: false
