version: otel_dataflow/v1
engine: { }
groups:
  default:
    pipelines:
      main:
        policies:
          channel_capacity:
            control:
              node: 100
              pipeline: 100
            pdata: 128

        nodes:
          receiver:
            type: syslog_cef:receiver
            config:
              protocol:
                udp:
                  listening_addr: "0.0.0.0:5140"
          exporter:
            type: perf:exporter
            config:
              frequency: 1000
              cpu_usage: false
              mem_usage: false
              disk_usage: false
              io_usage: false

        connections:
          - from: receiver
            to: exporter
