[package]
name = "otap-df-state"
description = "Internal state management for OTAP pipelines"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-config = { workspace = true }
otap-df-telemetry = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
flume = { workspace = true }
thiserror = { workspace = true }
tokio-util = { workspace = true }
tokio = { workspace = true }

# Note: use for tracing::field::debug() annotations, b/c otel_xxx! macros
# do not support directly. Consider whether to add or consolidate.
tracing = { workspace = true }
