[package]
name = "otap-df-controller"
description = "OTAP dataflow engine controller"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
testing = []

[dependencies]
otap-df-config = { path = "../config" }
otap-df-engine = { path = "../engine" }

thiserror = { workspace = true }
miette = { workspace = true }
tokio = { workspace = true }
core_affinity = "0.8.3"

[dev-dependencies]
serde_json = { workspace = true }
otap-df-otlp = { path = "../otlp" }