[package]
name = "data_engine_parser_macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
pest_meta = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-crate = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
data_engine_kql_parser = { path = "../../" }
data_engine_parser_abstractions = { path = "../../../parser-abstractions" }
pest = { workspace = true }
pest_derive = { workspace = true }
