[package]
name = "otap-df-opl"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
data_engine_expressions = { workspace = true }
data_engine_parser_abstractions = { workspace = true }
data_engine_parser_macros = { workspace = true }
data_engine_kql_parser = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }