[package]
name = "otap-df-opl"
description = "Observability Processing Language (OPL)"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
data_engine_parser_abstractions = { workspace = true }
data_engine_expressions = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }