[package]
name = "otap-df-pdata"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
otel-arrow-rust = { workspace = true }
otap-df-pdata-otlp-macros = { workspace = true }
otap-df-pdata-otlp-model = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]
prost = { workspace = true }

[lints]
workspace = true

[features]
bench = []
