[package]
name = "otap-df-query-engine"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
async-trait = { workspace = true }
datafusion = { workspace = true }
futures-core = { workspace = true }
parking_lot = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }
data_engine_expressions = { workspace = true }

otap-df-pdata = { path = "../pdata" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
data_engine_kql_parser = { workspace = true }
data_engine_parser_abstractions = { workspace = true }
pretty_assertions = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }

otap-df-opl = { path = "../opl" }

[[bench]]
name = "filter"
harness = false

[profile.bench]
opt-level = 3
debug = false
incremental = false
lto = "fat"
codegen-units = 1
panic = "abort"

[lints]
workspace = true
