[package]
name = "otap-df-syslog-cef"
description = "Syslog CEF receiver node"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-engine = { path = "../engine", features = ["testing"] }
otap-df-engine-macros = { path = "../engine-macros" }
otap-df-config = { path = "../config" }
otap-df-pdata-views = { path = "../pdata-views"}

# Workspace dependencies
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
portpicker = "0.1.1"