tests: 
  - name: "No Processor"
    pipeline_config_path: ./validation_pipelines/no-processor.yaml
    variables:
      loadgen_exporter_type: otlp
      backend_receiver_type: otlp
      transformitive: false
  - name: "Debug Processor"
    pipeline_config_path: ./validation_pipelines/debug-processor.yaml
    variables:
      loadgen_exporter_type: otap
      backend_receiver_type: otlp
      transformitive: false