name: "Tidy Renovate PRs"
permissions:
  contents: read

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  tidy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' && github.event.pull_request.head.repo.fork == false }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "1.25.5"
      - name: make genotelarrowcol
        # This also runs 'go mod tidy' as part of its process
        run: make genotelarrowcol
      - name: Commit changes
        run: |
          # Configure git for otelbot
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

          if ! git diff --exit-code; then
            git add .
            git commit -m "make genotelarrowcol"
            git push
          fi
